import {
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { device } from "./device";
import { user } from "./user";
import { workstation } from "./workstation";

/**
 * A code project synced from the TUI. The device's git repo is the source of truth; the
 * server keeps an ordered log of git bundles (`code_version`) that any paired device can
 * replay to rebuild the same history, plus the latest text files for the web viewer.
 */
export const codeProject = pgTable("code_project", {
  /** Generated by the TUI and kept in the repo's git config, so a rename does not fork it. */
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  workstationId: text("workstation_id")
    .notNull()
    .references(() => workstation.id, { onDelete: "cascade" }),
  createdBy: text("created_by")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  deviceId: text("device_id").references(() => device.id, {
    onDelete: "set null",
  }),
  /** Full commit sha of the newest version — what a push must build on to be accepted. */
  headSha: text("head_sha"),
  version: integer("version").notNull().default(0),
  /** JSON `{path: contents}` of the head's text files. Binaries and big files are left out. */
  files: text("files").notNull().default("{}"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const codeVersion = pgTable(
  "code_version",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id")
      .notNull()
      .references(() => codeProject.id, { onDelete: "cascade" }),
    version: integer("version").notNull(),
    commitSha: text("commit_sha").notNull(),
    /** The head this push built on; null for the first. */
    baseSha: text("base_sha"),
    message: text("message"),
    /**
     * `git bundle` of the commits in `baseSha..commitSha`, base64.
     * ponytail: bytes in Postgres; move to object storage if projects outgrow the 10 MB push cap.
     */
    bundle: text("bundle").notNull(),
    deviceId: text("device_id").references(() => device.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("code_version_commit_unique").on(
      table.projectId,
      table.commitSha,
    ),
  ],
);
