apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: jarvis-web
    newTag: dev
replicas:
  - name: api-server
    count: 1
  - name: reverse-proxy
    count: 1
